 # [START cloudbuild_npm_node]
steps:
# Install dependencies
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['install']
# Run custom commands
- name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['run', 'build']
  - name: gcr.io/cloud-builders/npm
  entrypoint: npm
  args: ['start']
# [END cloudbuild_npm_node]  
